### ISSUE TITLE
Help with milestone in redmine 2.1.0.

### ISSUE THREAD

**Issue by correajl** [k41n/redmine_milestones#15]
Hi! Congratulations for the plugin! Very nice!

We are using it here. I'm trying to migrate to redmine 2.1.0 and Milestone is the only plugin we hadn't get working. See the messages:
# RAILS_ENV=production rake db:migrate:plugin NAME=redmine_milestones --trace

*\* Invoke db:migrate:plugin (first_time)
*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
No such file to load -- dispatcher
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:225:in`require_dependency'
/opt/redmine-2.1.0/plugins/redmine_milestones/init.rb:10
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
/opt/redmine-2.1.0/lib/redmine/plugin.rb:130:in `load'
/opt/redmine-2.1.0/lib/redmine/plugin.rb:121:in`each'
/opt/redmine-2.1.0/lib/redmine/plugin.rb:121:in `load'
/opt/redmine-2.1.0/config/initializers/30-redmine.rb:13
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in`load'
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in`load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/engine.rb:588
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/engine.rb:587:in`each'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/engine.rb:587
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/initializable.rb:30:in`run'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/initializable.rb:55:in `run_initializers'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/initializable.rb:54:in`each'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/application.rb:136:in`initialize!'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `send'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in`method_missing'
/opt/redmine-2.1.0/config/environment.rb:14
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/application.rb:103:in `require'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/application.rb:103:in`require_environment!'
/var/lib/gems/1.8/gems/railties-3.2.8/lib/rails/application.rb:295:in `initialize_tasks'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `execute'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:157:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:157:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`run'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/var/lib/gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19
Tasks: TOP => db:migrate:plugin => redmine:plugins:migrate => environment

Thanks!

**Comment by correajl** [comment]
I've found something that seems similar:

http://www.redmine.org/boards/3/topics/30930

Thanks!

**Comment by CarinaMclane** [comment]
I'm having this same issue - I tried the fix suggetsed in the topic pasted, but this didn't work for me. Did you get it working?

**Comment by ghost** [comment]
Hi,

which branch did you use? The redmine-2.x branch installs here without a problem on a redmine 2.1.2 installation. The only problem is the filter on the gantt diagrams as reported here:

https://github.com/k41n/redmine_milestones/issues/17

**Comment by ahnkle** [comment]
I am having the same problem.

I changed Dispatcher.to_prepare as mentioned in the link above, in lib/milestones/mailer_patch.rb and lib/milestones/query_patch.rb but I now get the error:

<pre>
 $ RAILS_ENV=production rake redmine:plugins:migrate NAME=redmine_milestones
(in /opt/redmine-2.1)
rake aborted!
undefined method `[]' for nil:NilClass
/opt/redmine-2.1/plugins/redmine_milestones/lib/milestones/mailer_patch.rb:31:in `block in included'
/opt/redmine-2.1/plugins/redmine_milestones/lib/milestones/mailer_patch.rb:29:in `class_eval'
/opt/redmine-2.1/plugins/redmine_milestones/lib/milestones/mailer_patch.rb:29:in `included'
/opt/redmine-2.1/plugins/redmine_milestones/init.rb:41:in `include'
/opt/redmine-2.1/plugins/redmine_milestones/init.rb:41:in `<top (required)>'
/opt/redmine-2.1/lib/redmine/plugin.rb:130:in `block in load'
/opt/redmine-2.1/lib/redmine/plugin.rb:121:in `each'
/opt/redmine-2.1/lib/redmine/plugin.rb:121:in `load'
/opt/redmine-2.1/config/initializers/30-redmine.rb:13:in `<top (required)>'
/opt/redmine-2.1/config/environment.rb:16:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
</pre>

**Comment by tomposmiko** [comment]
hi,

We have the same issue on redmine 2.2. Is there any fix for this?

Thank you

**Comment by cforce** [comment]
same here on 2.2 also
