### ISSUE TITLE
davidsielert/redmine_milestones - redmine 2.2 not working -undefined method `available_filters' for class `Query'

### ISSUE THREAD

**Issue by cforce** [k41n/redmine_milestones#22]
on redmine db:migrate i get follwing error:

[rake --tasks] rake aborted!
undefined method `available_filters' for class`Query'
org/jruby/RubyModule.java:2292:in `alias_method'
/home/sidfunktion/DevMine_WK/infomine-2.2/plugins/redmine_milestones/lib/milestones/query_patch.rb:14:in`included'
org/jruby/RubyModule.java:2313:in `module_eval'
/home/sidfunktion/DevMine_WK/infomine-2.2/plugins/redmine_milestones/lib/milestones/query_patch.rb:8:in`included'
org/jruby/RubyModule.java:2095:in `include'
org/jruby/RubyBasicObject.java:1673:in`**send**'
org/jruby/RubyKernel.java:2081:in `send'
redmine/plugins/redmine_milestones/init.rb:38:in`(root)'
org/jruby/RubyKernel.java:1019:in `require'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in`require'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in`require'
redmine/lib/redmine/plugin.rb:1:in `(root)'
org/jruby/RubyArray.java:1612:in`each'
redmine/lib/redmine/plugin.rb:130:in `load'
redmine/lib/redmine/plugin.rb:121:in`load'
org/jruby/RubyKernel.java:1045:in `load'
redmine/config/initializers/30-redmine.rb:12:in`(root)'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:1:in`(root)'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
org/jruby/RubyArray.java:1612:in`each'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
org/jruby/RubyBasicObject.java:1728:in`instance_exec'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/initializable.rb:30:in `run'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/engine.rb:588:in`Engine'
org/jruby/RubyArray.java:1612:in `each'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/engine.rb:587:in`Engine'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/initializable.rb:55:in `run_initializers'
org/jruby/RubyBasicObject.java:1667:in`**send**'
org/jruby/RubyKernel.java:2077:in `send'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/initializable.rb:54:in`run_initializers'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/application.rb:136:in `initialize!'
org/jruby/RubyKernel.java:1019:in`require'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in`load_dependency'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/railtie/configurable.rb:30:in`method_missing'
org/jruby/RubyKernel.java:1045:in `load'
redmine/config/environment.rb:14:in`(root)'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
redmine/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:1:in`(root)'
redmine/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:32:in `(root)'
org/jruby/RubyArray.java:1612:in`each'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:1:in `(root)'
org/jruby/RubyKernel.java:1045:in`load'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in`load_dependency'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
redmine/lib/tasks/redmine.rake:126:in`(root)'
org/jruby/RubyArray.java:1612:in `each'
redmine/lib/tasks/redmine.rake:126:in`(root)'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:1:in `(root)'
org/jruby/RubyBasicObject.java:1667:in`**send**'
org/jruby/RubyKernel.java:2077:in `send'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in`load'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:245:in `load'
org/jruby/RubyKernel.java:1045:in`load'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/engine.rb:425:in `load_tasks'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/engine.rb:425:in`load_tasks'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/application.rb:145:in `load_tasks'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/railties-3.2.9/lib/rails/railtie/configurable.rb:30:in`method_missing'
redmine/Rakefile:7:in `(root)'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/rake-10.0.3/lib/rake/rake_module.rb:1:in`(root)'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/rake-10.0.3/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/rake-10.0.3/lib/rake/application.rb:583:in`raw_load_rakefile'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/gems/rake-10.0.3/lib/rake/application.rb:89:in `load_rakefile'
org/jruby/RubyKernel.java:1045:in`load'
/home/sidfunktion/.rvm/gems/jruby-1.7.0/bin/rake:19:in `(root)'

**Comment by cforce** [comment]
my wrong, this error is result of a wrong pull from redmine github repo.
