### ISSUE TITLE
Redmine 2.6 - cannot install

### ISSUE THREAD

**Issue by Yumash** [k41n/redmine_milestones#47]
Would you fix it for the new redminers?

```
root@redmine:/var/redmine/plugins/redmine_milestones# rake redmine:plugins:migrate RAILS_ENV=production
(in /var/redmine)
rake aborted!
LoadError: No such file to load -- dispatcher
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:317:in `rescue in depend_on'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:312:in `depend_on'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:225:in `require_dependency'
/var/redmine/plugins/redmine_milestones/init.rb:10:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/var/redmine/lib/redmine/plugin.rb:150:in `block in load'
/var/redmine/lib/redmine/plugin.rb:141:in `each'
/var/redmine/lib/redmine/plugin.rb:141:in `load'
/var/redmine/config/initializers/30-redmine.rb:19:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:103:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by eurodba** [comment]
Hi, did you found solution?

**Comment by vincent** [comment]
It seems you're still on the master branch. Try to `git checkout redmine-2.x` before migrating
